---

- name: ansible create directory example
  become: yes
  file:
    path: /tmp/.ansible
    mode: '0777'
    state: directory

- name: Install slurmd and dependencies
  become: yes
  ansible.builtin.package:
    name:
      - slurmd
      - ntp
      - munge
      - libmunge-dev
      - libmunge2
    state: present

- name: copy munge.key to /etc/munge/
  become: yes
  ansible.builtin.copy:
    src: munge.key
    dest: /etc/munge/
    mode: '0400'


- name: start munge service
  become: yes
  ansible.builtin.service:
    name: slurmd
    state: started

- name: reload munge service
  become: yes
  ansible.builtin.service:
    name: munge
    state: restarted
